version: '2'
services:
    mariadb:
        image: mariadb:10.2.9
        container_name: docker_db
        hostname: docker_db
        expose:
          - "3306"
        volumes:
          - ./data:/var/lib/mysql
          - /etc/localtime:/etc/localtime
        environment:
          - MYSQL_ROOT_PASSWORD=bangtan
        networks:
          net:
            ipv4_address: 172.70.0.2
    web:
        image: php/7.2.10
        container_name: docker
        hostname: docker
        privileged: true
        ports:
            - "7200:80"
            - "7443:443"
        expose:
            - "80"
            - "443"
        volumes:
            - /home/$USER/public_html:/var/www/html/
            - ./logs:/var/log/apache2
            - ./conf:/etc/apache2/sites-enabled/
            - ./certs:/usr/local/apache2/certs
        networks:
            net:
                ipv4_address: 172.70.0.3
networks:
    net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.70.0.0/16
