version: '2'
services:
    web:
        image: php/7.2.10
        container_name: php_7.2.10
        hostname: php_7.2.10
        privileged: true
        ports:
            - "7200:80"
            - "7443:443"
        expose:
            - "80"
            - "443"
        volumes:
            - /home/$USER/public_html:/var/www/html/
            - ./logs:/var/log/apache2
            - ./conf:/etc/apache2/sites-enabled/
            - ./certs:/usr/local/apache2/certs
        networks:
            net:
                ipv4_address: 172.70.0.3
networks:
    net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.70.0.0/16
